import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Shop Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="mb-20 overflow-hidden">
          <Navbar />
        </div>
        <div className="container pt-10 md:pt-0 mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </div>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
